--------------------------------------------------------
--  Constraints for Table AUTO_MODE_SUMMARY
--------------------------------------------------------

  ALTER TABLE "AUTO_MODE_SUMMARY" MODIFY ("ELNOT" NOT NULL ENABLE);
  ALTER TABLE "AUTO_MODE_SUMMARY" MODIFY ("PARM" NOT NULL ENABLE);
  ALTER TABLE "AUTO_MODE_SUMMARY" MODIFY ("MODE_ID" NOT NULL ENABLE);
  ALTER TABLE "AUTO_MODE_SUMMARY" MODIFY ("MIN" NOT NULL ENABLE);
  ALTER TABLE "AUTO_MODE_SUMMARY" MODIFY ("MAX" NOT NULL ENABLE);
