REM INSERTING into AUTO_MODE_SUMMARY
SET DEFINE OFF;
Insert into AUTO_MODE_SUMMARY (ELNOT,PARM,MODE_ID,MIN,MAX) values ('NODET','RF',1,99,101.1);
Insert into AUTO_MODE_SUMMARY (ELNOT,PARM,MODE_ID,MIN,MAX) values ('NODET','RF',2,199,201.1);
commit;
